### PR TITLE
Update: all-contributors features added

### PR DESCRIPTION
**Pull request by Juancxh**

### CODE REVIEW

**Comment by paulotijero** [comment]
@all-contributors please add @Juancxh for code

**Review by paulotijero — APPROVED** [review]
I made a few small changes that I think will work. I leave them approving, but you would check them before merging it @Juancxh

**Comment by paulotijero** [comment]
@Juancxh Let's try without the added section because now we are adding a template in .allcontributorssrc if it doesn't work, in another PR let's see how to solve it.
badgeTemplate =>  https://github.com/opentech-pe/opentech.pe/pull/71/commits/72230df3e98907087c7df9a5ec2c52752c34d435#diff-c47fb5a6d4fde805d2706fc934e8d354R7

**Review by paulotijero — APPROVED** [review]
@Juancxh Let's try without the added section because now we are adding a template in .allcontributorssrc if it doesn't work, in another PR let's see how to solve it.
badgeTemplate =>  https://github.com/opentech-pe/opentech.pe/pull/71/commits/72230df3e98907087c7df9a5ec2c52752c34d435#diff-c47fb5a6d4fde805d2706fc934e8d354R7

**Comment by Juancxh** [comment]
I didn't quite understand what you mean, but I removed the part that generates the badge
https://github.com/opentech-pe/opentech.pe/pull/71/commits/99b3a8e5957bd5b0279496b7b8e4ece5092af232

**Review by paulotijero — APPROVED** [review]

**Comment by paulotijero** [comment]
@all-contributors please add @Juancxh for code

**Comment by Juancxh** [comment]
I'm not sure why it gave an error, but I think I found the solution: https://image.prntscr.com/image/8ums3mXDS3GKix3JLqsb5w.png

**Comment by Juancxh** [comment]
I'm not sure why it gave an error, but I think I found the solution: https://github.com/opentech-pe/opentech.pe/commit/709f0779c39169deb76ebaa11ce21ab5737e1741

**Pull request merged**
